import type { Subject } from "@/types";

export const SUBJECTS: Subject[] = [
  {
    id: "math2",
    name: "수학 II",
    subtitle: "Mathematics II",
    description: "함수의 극한과 연속, 미분법, 적분법의 기초",
    icon: "📐",
    gradient: "from-violet-600 to-indigo-600",
    units: [
      {
        id: "limit-of-function",
        name: "함수의 극한",
        description: "함수의 극한값, 극한의 성질, 연속함수",
        icon: "∞",
        conceptCount: 0,
        color: "text-primary",
      },
      {
        id: "derivative",
        name: "미분계수와 도함수",
        description: "미분계수의 정의, 도함수, 미분법 공식",
        icon: "𝑓′",
        conceptCount: 0,
        color: "text-primary",
      },
      {
        id: "extrema",
        name: "함수의 증감과 극대·극소",
        description: "증가/감소, 극값 판정, 그래프 개형",
        icon: "📈",
        conceptCount: 0,
        color: "text-primary",
      },
      {
        id: "definite-integral",
        name: "정적분과 넓이",
        description: "정적분의 정의, 넓이 계산, 급수와 적분",
        icon: "∫",
        conceptCount: 0,
        color: "text-primary",
      },
    ],
  },
  {
    id: "calculus",
    name: "미적분",
    subtitle: "Calculus",
    description: "급수, 여러 가지 미분법, 적분법과 활용",
    icon: "∂",
    gradient: "from-emerald-600 to-teal-600",
    units: [
      {
        id: "series-convergence",
        name: "급수의 수렴/발산",
        description: "무한급수, 수렴 판정법, 등비급수",
        icon: "Σ",
        conceptCount: 0,
        color: "text-success",
      },
      {
        id: "differentiation-methods",
        name: "여러 가지 미분법",
        description: "합성함수, 매개변수, 음함수 미분",
        icon: "∂",
        conceptCount: 0,
        color: "text-success",
      },
      {
        id: "substitution-integral",
        name: "치환적분",
        description: "치환적분법, 부분적분법",
        icon: "∮",
        conceptCount: 0,
        color: "text-success",
      },
      {
        id: "velocity-acceleration",
        name: "속도와 가속도",
        description: "위치·속도·가속도의 관계, 운동 해석",
        icon: "🚀",
        conceptCount: 0,
        color: "text-success",
      },
      {
        id: "volume-of-revolution",
        name: "회전체의 부피",
        description: "x축/y축 회전, 디스크·와셔법",
        icon: "🔄",
        conceptCount: 0,
        color: "text-amber",
      },
    ],
  },
  {
    id: "geometry",
    name: "기하와 벡터",
    subtitle: "Geometry & Vectors",
    description: "이차곡선, 평면벡터, 공간도형",
    icon: "🔷",
    gradient: "from-rose-600 to-pink-600",
    units: [
      {
        id: "conic-sections",
        name: "이차곡선",
        description: "포물선, 타원, 쌍곡선의 방정식과 성질",
        icon: "⭕",
        conceptCount: 0,
        color: "text-error",
      },
      {
        id: "vector-operations",
        name: "벡터의 연산과 내적",
        description: "벡터 덧셈, 스칼라배, 내적, 수직·평행",
        icon: "→",
        conceptCount: 0,
        color: "text-error",
      },
      {
        id: "space-geometry",
        name: "공간도형과 좌표",
        description: "공간좌표, 구의 방정식, 평면의 방정식",
        icon: "🧊",
        conceptCount: 0,
        color: "text-error",
      },
    ],
  },
  {
    id: "math1",
    name: "수학 I",
    subtitle: "Mathematics I",
    description: "삼각함수, 지수·로그함수, 수열의 기초",
    icon: "📊",
    gradient: "from-amber-500 to-orange-600",
    units: [
      {
        id: "trig-functions",
        name: "삼각함수",
        description: "단위원, sin·cos·tan 그래프, 삼각함수 합성",
        icon: "🎯",
        conceptCount: 0,
        color: "text-amber",
      },
      {
        id: "exp-log",
        name: "지수·로그함수",
        description: "지수함수, 로그함수, 역함수 대칭, 자연로그 e",
        icon: "📈",
        conceptCount: 0,
        color: "text-amber",
      },
      {
        id: "sequences",
        name: "수열",
        description: "등차수열, 등비수열, 시그마 합, 급수 수렴",
        icon: "Σ",
        conceptCount: 0,
        color: "text-amber",
      },
    ],
  },
  {
    id: "prob-stat",
    name: "확률과 통계",
    subtitle: "Probability & Statistics",
    description: "확률 시뮬레이션, 정규분포, 순열과 조합",
    icon: "🎲",
    gradient: "from-sky-500 to-blue-600",
    units: [
      {
        id: "probability",
        name: "확률",
        description: "주사위·동전 시뮬레이션, 큰 수의 법칙, 조건부 확률",
        icon: "🎲",
        conceptCount: 0,
        color: "text-info",
      },
      {
        id: "normal-dist",
        name: "정규분포",
        description: "벨커브, 표준정규분포, 넓이=확률",
        icon: "🔔",
        conceptCount: 0,
        color: "text-info",
      },
      {
        id: "combinations",
        name: "순열과 조합",
        description: "nPr, nCr, 파스칼 삼각형, 이항분포",
        icon: "🔢",
        conceptCount: 0,
        color: "text-info",
      },
    ],
  },
  {
    id: "middle-geo",
    name: "중등 기하",
    subtitle: "Middle School Geometry",
    description: "삼각비, 원의 성질, 작도",
    icon: "📐",
    gradient: "from-teal-500 to-cyan-600",
    units: [
      {
        id: "trig-ratios",
        name: "삼각비",
        description: "직각삼각형, sin·cos·tan 비율, 특수각",
        icon: "△",
        conceptCount: 0,
        color: "text-success",
      },
      {
        id: "circle-properties",
        name: "원의 성질",
        description: "원주각, 중심각, 접선, 내접 사각형",
        icon: "⊙",
        conceptCount: 0,
        color: "text-success",
      },
      {
        id: "construction",
        name: "작도",
        description: "자와 컴퍼스를 이용한 기본 작도",
        icon: "✏️",
        conceptCount: 0,
        color: "text-success",
      },
    ],
  },
];

export function getSubject(id: string): Subject | undefined {
  return SUBJECTS.find((s) => s.id === id);
}

export function getUnit(subjectId: string, unitId: string) {
  const subject = getSubject(subjectId);
  return subject?.units.find((u) => u.id === unitId);
}
